### ISSUE TITLE
ionic build ios fails with Cannot read property 'AssetUrl' error

### ISSUE THREAD

**Issue by timofeysie** [driftyco/ionic-preview-app#66]
On Mac OS Sierra 10.12.
cloned, npm i, ionic platform add ios, all good.
Then ionic build ios fails with the following output:
```
[15:02:17]  lint started ... 
[15:02:18]  /Users/timcurchod/repos/ionic-preview-app/node_modules/@angular/compiler-cli/src/private_import_compiler.js:10 
[15:02:18]  exports.AssetUrl = compiler_1.__compiler_private__.AssetUrl; 
[15:02:18]  TypeError: Cannot read property 'AssetUrl' of undefined 
[15:02:18]  ngc failed 
[15:02:18]  ionic-app-script task: "build" 
[15:02:18]  Error: Error 
```

**Comment by quangpdt** [comment]
The currently workaround solution is remove all character "^" in package version in package.json.

Hope this help! :)

**Comment by brandyscarney** [comment]
Thanks! This should be fixed now, please let me know if it isn't!

**Comment by timofeysie** [comment]
Thanks for the reply.  I removed all the '^' characters from the packages in the package.json file to fix the dependencies.  Then, did $ ionic serve, app works in the browser.
Next, $ ionic build ios, and the build still fails:
```
[10:01:39]  lint finished in 2.51 s 
[10:02:00]  Error: Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'AdvancedMapPage' from external module 
            "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/cards/advanced-map/pages" but cannot 
            be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'AdvancedSocialPage' from external 
            module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/cards/advanced-social/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'AvatarPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/lists/avatar/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BackgroundPage' from external module 
            "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/cards/background/pages" but cannot 
            be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BadgesPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/tabs/badges/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/action-sheets/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/alerts/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/badges/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/buttons/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/cards/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/checkboxes/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/datetime/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/fabs/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/gestures/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/grid/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/icons/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/inputs/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/lists/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/loading/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/menus/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/modals/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/navigation/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/popovers/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/radios/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/ranges/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/searchbars/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/segments/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/selects/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/slides/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported function has or is using name 'BasicPage' from external module "/Users/timcurchod/repos/ionic-preview-app/.tmp/pages/tabs/basic/pages" 
            but cannot be named. 
[10:02:00]  Error at /Users/timcurchod/repos/ionic-preview-app/.tmp/directives/helpers.ts:64:17 
[10:02:00]  Return type of exported functi 
[10:02:00]  ngc failed 
[10:02:00]  ionic-app-script task: "build" 
[10:02:00]  Error: Error 

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "--color"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! ionic-hello-world@ build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ build script 'ionic-app-scripts build'.
```

**Comment by quangpdt** [comment]
I have same problem with you yesterday, I just know the problem come from helper.ts file

> import * as buttons from '../pages/buttons/buttons';

Just need to comment out those import. I know this is not a solution but have no idea.

Anyway, @brandyscarney said it ticket #67 , this should be fixed in latest version. You can check and close this ticket ;)
